name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    # We're running on ubuntu-latest, nothing special
    runs-on: ubuntu-latest
    steps:
      # As usual, we simply checkout the project
      - name: Checkout
        uses: actions/checkout@v2

      # This action is provided by Cypress. It installs node and the NPM
      # dependencies, and caches them.
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # NOTE: we don't actually run tests here!
          runTests: false

      # Now we run our lints. This is the place where you could run other tests
      # unrelated to cypress (e.g.: unit tests).
      - name: Run lints
        run: npm run lint

      # Now we're building the svelte site.
      # This step generates a build/ directory.
      - name: Build site
        run: npm run build

      # And lastly, we upload the generated build/ folder as artifact so we can
      # use it in later steps.
      - name: Upload build and .svelte-kit folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: build
